-- RLS policies for the Control Plane platform tables.
--
-- Deliberately empty of permissive policies. RLS is enabled on every table by
-- migration 00001, and a table with RLS enabled and no policy denies all access
-- to any role that cannot bypass RLS. That is the correct starting position: the
-- Control Plane holds every customer organization, subscription, and entitlement
-- on the platform, so the cost of shipping a policy that is too permissive is
-- far higher than the cost of one that is missing.
--
-- WHY THERE IS NOTHING HERE
--
-- The generated policies used to be written against Supabase Auth:
--
--   create policy "subscriptions_select_own_org"
--     on public.subscriptions for select
--     using (auth.role() = 'authenticated');
--
-- Two things were wrong with that. It applied no organization scoping at all,
-- so any authenticated user could read every subscription on the platform. And
-- it could never have worked as intended anyway: the Control Plane authenticates
-- through ZITADEL, so no Supabase JWT is ever presented and auth.role() is
-- always NULL. Some of those policies denied by accident and one leaked, with
-- nothing to distinguish the two.
--
-- A companion policy naming service_role was dead code besides. That role
-- carries BYPASSRLS, so a policy attached to it is never evaluated.
--
-- HOW TO ADD POLICIES
--
-- Decide first what identifies a caller. Because identity comes from ZITADEL
-- rather than Supabase Auth, the API must declare it -- typically as
-- transaction-scoped settings read by helper functions, with requests running as
-- a role that cannot bypass RLS. Then ship each policy as a numbered migration
-- rather than adding it here: a policy is part of the schema and its security
-- surface, and this directory is re-applied on top of the migrations, so a
-- policy defined in both places silently resolves to whichever version this file
-- holds.
--
-- Write the isolation tests before the policies. A policy suite that has never
-- been observed to fail has not been tested.
