import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname, relative, sep } from 'node:path'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'
import { z } from 'zod'
import type { GenerationContext } from './context.js'
import { listProfiles, isValidProfile } from '../profiles/loader.js'

/**
 * The KORAS project manifest — `.koras/project.yaml`.
 *
 * Every generated repository carries one, whatever its profile. It is the
 * authoritative answer to "which starter generated this repository, under which
 * profile, at which versions" — previously only inferable from
 * `infrastructure/terraform/terraform.tfvars`, which is a provisioning input
 * rather than an identity record.
 *
 * This is a stable platform contract. Future tooling (`koras doctor`,
 * `koras upgrade`, `koras diff-starter`, `koras project:info`, and Control
 * Plane registration) reads it, so `schema_version` is not to be changed
 * without an explicit migration design.
 *
 * References only — no secrets, no credentials, no endpoints. The file is
 * safe to commit, and the generated `.gitignore` deliberately does not exclude it.
 */

const STARTER_ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../../..')

/** Canonical location, relative to the generated project root. */
export const PROJECT_MANIFEST_PATH = '.koras/project.yaml'

export const GENERATOR_NAME = 'create-koras-app'

/** Only bump alongside a manifest migration design. */
export const PROJECT_MANIFEST_SCHEMA_VERSION = 1

// ── Types ───────────────────────────────────────────────────────────────────

export type KorasProjectProfile = 'product' | 'control-plane'

export interface KorasProjectManifest {
  schema_version: typeof PROJECT_MANIFEST_SCHEMA_VERSION
  project: {
    name: string
    slug: string
    profile: KorasProjectProfile
  }
  generator: {
    name: typeof GENERATOR_NAME
    starter_version: string
    profile_version: string
    /**
     * Fingerprint of the profile tree this project was generated from.
     *
     * Optional, because manifests written before it existed must keep
     * validating.
     *
     * `starter_version` reads the workspace `package.json`, which is a release
     * number a person maintains — and across every change the starter made in
     * its first weeks it stayed at 0.1.0, so nothing downstream could tell a
     * current project from one generated a month earlier. A field that only
     * moves when someone remembers to move it cannot signal staleness.
     *
     * This one moves on its own: it is a digest of the profile's manifest,
     * defaults and every file in its template. Two projects with the same
     * digest were generated from the same definition; a different digest says
     * the definition changed, without saying whether the change matters.
     */
    template_digest?: string
  }
  /**
   * The components this project was generated with.
   *
   * Optional, because manifests written before this field existed must keep
   * validating. Its absence means "generated by an older starter", which is
   * information rather than an error — but tooling that needs to re-render
   * anything for this project cannot do so safely without it, since the only
   * other record of the selections is `terraform.tfvars`, a provisioning input
   * an operator may edit.
   */
  components?: {
    applications: string[]
    services: string[]
    capabilities: string[]
  }
}

// ── Schema ──────────────────────────────────────────────────────────────────

// The official semver.org reference pattern. Versions reach the manifest from
// files a human edits, so they are validated rather than trusted.
const SEMVER_RE =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

export const semverSchema = z
  .string()
  .regex(SEMVER_RE, 'must be a semantic version, for example 1.0.0')

/**
 * Reusable schema — validation on write here, and the parser for any future
 * command that needs to read a generated project's manifest.
 */
export const KorasProjectManifestSchema = z.object({
  schema_version: z.literal(PROJECT_MANIFEST_SCHEMA_VERSION),
  project: z.object({
    name: z.string().min(1, 'must not be empty'),
    slug: z.string().min(1, 'must not be empty'),
    profile: z.enum(['product', 'control-plane']),
  }),
  generator: z.object({
    name: z.literal(GENERATOR_NAME),
    starter_version: semverSchema,
    profile_version: semverSchema,
    template_digest: z
      .string()
      .regex(/^[0-9a-f]{64}$/, 'must be a sha256 digest in lower-case hex')
      .optional(),
  }),
  // Optional so that a manifest predating this field still parses. Adding an
  // optional field is backward compatible, so schema_version does not move.
  components: z
    .object({
      applications: z.array(z.string()),
      services: z.array(z.string()),
      capabilities: z.array(z.string()),
    })
    .optional(),
})

// ── Version resolution ──────────────────────────────────────────────────────

/**
 * A digest of everything that defines a profile.
 *
 * Paths are sorted and included in the hash alongside the bytes, so renaming a
 * file changes the digest even when its contents do not — a rename is a change
 * to what gets generated.
 *
 * Deliberately not a digest of the rendered output: that varies with the
 * project name, so two projects generated from one definition would disagree
 * and the field would answer a different question than the one asked of it.
 */
// A space is a legal filename character and a NUL is not, so only NUL is an
// unambiguous delimiter here.
// A space is a legal filename character and a NUL is not, so only NUL is an
// unambiguous delimiter between a path and the bytes that follow it.
const NUL = Buffer.from([0])

/**
 * Collapses CRLF to LF so the digest describes the profile's content rather
 * than the checkout it was computed in.
 *
 * `.gitattributes` sets `* text=auto`, so a template file is LF in the object
 * store and CRLF in a Windows working tree. Hashing the raw bytes therefore
 * produced one digest on Windows and a different one in CI for the same
 * profile -- and worse, a digest written before a merge stopped matching after
 * it, because the checkout rewrote the very files being hashed. That is the
 * same failure the separator normalisation below was added to prevent; line
 * endings were the half that got missed.
 *
 * A twin of `toUnixLineEndings` in writer.ts, duplicated rather than imported
 * because writer.ts already imports this module and the cycle is not worth a
 * shared module for four lines. That one decides what gets written; this one
 * only feeds a hash.
 */
export function normalizeForDigest(content: Buffer): Buffer {
  return content.includes('\r\n')
    ? Buffer.from(content.toString('utf8').replace(/\r\n/g, '\n'))
    : content
}

export function resolveTemplateDigest(profile: string): string {
  const root = join(STARTER_ROOT, 'profiles', profile)
  const files: string[] = []

  const walk = (directory: string): void => {
    for (const entry of readdirSync(directory).sort()) {
      const full = join(directory, entry)
      if (statSync(full).isDirectory()) walk(full)
      else files.push(full)
    }
  }
  walk(root)

  const hash = createHash('sha256')
  for (const file of files.sort()) {
    // Separators are normalised so a digest computed on Windows matches one
    // computed in CI. Without it every project would read as stale to half the
    // people who checked it.
    hash.update(relative(root, file).split(sep).join('/'))
    hash.update(NUL)
    hash.update(normalizeForDigest(readFileSync(file)))
    hash.update(NUL)
  }
  return hash.digest('hex')
}

/**
 * Version of the KORAS SaaS Starter that generated the project, read from the
 * workspace root `package.json` — the repository's single canonical version.
 *
 * Read at generation time rather than baked in at build time, so a locally
 * built generator reports the tree it actually came from. There is deliberately
 * no fallback: a manifest claiming "unknown" would be worse than a failed
 * generation, because downstream tooling would trust it.
 */
export function resolveStarterVersion(): string {
  const pkgPath = join(STARTER_ROOT, 'package.json')
  let pkg: { name?: unknown; version?: unknown }
  try {
    pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as typeof pkg
  } catch (err) {
    throw new Error(
      `Could not resolve the starter version from ${pkgPath}: ${String(err)}\n` +
        '  The generator writes this into every project\'s .koras/project.yaml.',
    )
  }

  const version = pkg.version
  if (typeof version !== 'string' || !SEMVER_RE.test(version)) {
    throw new Error(
      `The starter version in ${pkgPath} is not a semantic version ` +
        `(found: ${JSON.stringify(version)}).\n` +
        '  Fix the root package.json "version" field before generating.',
    )
  }
  return version
}

/**
 * Version of the selected profile, read from its manifest. Independent of the
 * starter version: a starter fix ships without touching profile behaviour,
 * while a breaking profile structure change bumps this.
 */
export function resolveProfileVersion(ctx: GenerationContext): string {
  const version = ctx.manifest.version
  if (!SEMVER_RE.test(version)) {
    throw new Error(
      `Profile "${ctx.profile}" declares version "${version}", which is not a ` +
        'semantic version.\n' +
        `  Fix the "version" field in profiles/${ctx.profile}/manifest.yaml.`,
    )
  }
  return version
}

// ── Construction, validation, serialization ─────────────────────────────────


/**
 * The enabled component keys, sorted so a manifest is stable across runs.
 *
 * Only what is on: an explicit `false` and an absent key mean the same thing to
 * every consumer, and recording both invites them to diverge.
 */
function enabledComponents(ctx: GenerationContext): NonNullable<KorasProjectManifest['components']> {
  const on = (selected: Record<string, boolean>): string[] =>
    Object.entries(selected)
      .filter(([, enabled]) => enabled)
      .map(([name]) => name)
      .sort()

  return {
    applications: on(ctx.selections.applications),
    services: on(ctx.selections.services),
    capabilities: on(ctx.selections.capabilities),
  }
}

export function buildProjectManifest(ctx: GenerationContext): KorasProjectManifest {
  // A profile that is not one of the supported set must never reach a written
  // manifest — Control Plane tooling gates on this field before it provisions.
  if (!isValidProfile(ctx.profile)) {
    throw new Error(
      `Cannot write ${PROJECT_MANIFEST_PATH}: unsupported profile ` +
        `"${String(ctx.profile)}".\n` +
        `  Supported profiles: ${listProfiles().join(', ')}`,
    )
  }

  // Key order is fixed here, and js-yaml preserves insertion order, so
  // serialization is deterministic for a given context.
  const manifest: KorasProjectManifest = {
    schema_version: PROJECT_MANIFEST_SCHEMA_VERSION,
    project: {
      name: ctx.projectName,
      slug: ctx.projectSlug,
      profile: ctx.profile,
    },
    generator: {
      name: GENERATOR_NAME,
      starter_version: resolveStarterVersion(),
      profile_version: resolveProfileVersion(ctx),
      template_digest: resolveTemplateDigest(ctx.profile),
    },
    components: enabledComponents(ctx),
  }

  return validateProjectManifest(manifest, 'generated')
}

/** Throws with the failing field paths rather than writing an invalid manifest. */
export function validateProjectManifest(value: unknown, source: string): KorasProjectManifest {
  const result = KorasProjectManifestSchema.safeParse(value)
  if (!result.success) {
    const issues = result.error.issues.map((i) => `  ${i.path.join('.')}: ${i.message}`).join('\n')
    throw new Error(`Invalid KORAS project manifest (${source}):\n${issues}`)
  }
  return result.data
}

/** Parses and validates a manifest read back from disk. */
export function parseProjectManifest(contents: string, source: string): KorasProjectManifest {
  let raw: unknown
  try {
    raw = yaml.load(contents)
  } catch (err) {
    throw new Error(`${source} is not valid YAML: ${String(err)}`)
  }
  return validateProjectManifest(raw, source)
}

export function serializeProjectManifest(manifest: KorasProjectManifest): string {
  const header =
    '# KORAS project manifest — generated by create-koras-app.\n' +
    '# Identifies this repository to KORAS tooling. Safe to commit: it holds\n' +
    '# references only, never secrets. Regenerate rather than editing by hand.\n'
  // `sortKeys` is left off so the emitted order matches the declared shape:
  // schema_version, project, generator. `lineWidth: -1` disables line folding.
  return header + yaml.dump(manifest, { lineWidth: -1, noRefs: true, sortKeys: false })
}

export function renderProjectManifest(ctx: GenerationContext): string {
  return serializeProjectManifest(buildProjectManifest(ctx))
}
