"""Extract the real OpenAPI schema from a KORAS FastAPI service.

This is the only source of truth the Postman generator trusts. It imports the
service's actual `FastAPI` app object and calls `app.openapi()` -- the same
method FastAPI itself uses to serve `/openapi.json` -- so the output reflects
the routes, parameters, request/response models and status codes that are
really registered, not what a document says should be there.

It does not start the app (no lifespan, no database connection, no outbound
call). `Settings()` still validates at import time, though, so any field with
no default must be present in the environment. This script fills those with
placeholder values *only when the caller has not already set them*, which
keeps a real `.env`-backed shell (e.g. one loaded via `doppler run`) authoritative
and makes CI/offline extraction work without secrets.

Usage:
    python extract_openapi.py --service-dir <path/to/services/api> --out <file.json>

The service dir must contain `koras_api/main.py` exposing `app` -- true for
every KORAS Control Plane and product API generated by this starter.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import sys
from pathlib import Path

# Values used only to satisfy pydantic-settings at import time when the real
# ones are not already in the environment. They are never sent anywhere --
# `app.openapi()` builds the schema from route declarations and Pydantic
# models, and touches neither the database nor Redis nor ZITADEL.
_PLACEHOLDER_ENV: dict[str, str] = {
    "ENVIRONMENT": "dev",
    "DATABASE_URL": "postgresql://user:pass@localhost:5432/db",
    "REDIS_URL": "redis://localhost:6379/0",
    "ZITADEL_DOMAIN": "dev.zitadel.example.com",
    "ZITADEL_PROJECT_ID": "000000000000000000",
}


def _fill_placeholder_env() -> None:
    for key, value in _PLACEHOLDER_ENV.items():
        os.environ.setdefault(key, value)


def extract(service_dir: Path) -> dict:
    _fill_placeholder_env()
    sys.path.insert(0, str(service_dir))
    module = importlib.import_module("koras_api.main")
    app = getattr(module, "app", None)
    if app is None:
        raise SystemExit(f"koras_api.main in {service_dir} has no `app` object")
    schema = app.openapi()
    return schema


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--service-dir",
        required=True,
        type=Path,
        help="Path to the service's services/api directory (contains koras_api/main.py)",
    )
    parser.add_argument("--out", required=True, type=Path, help="Where to write the OpenAPI JSON")
    args = parser.parse_args()

    schema = extract(args.service_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(schema, indent=2, sort_keys=False), encoding="utf-8")
    paths = schema.get("paths", {})
    operations = sum(
        1
        for methods in paths.values()
        for method in methods
        if method.lower() in {"get", "post", "put", "patch", "delete"}
    )
    print(
        f"extracted {schema.get('info', {}).get('title', 'API')}: "
        f"{len(paths)} paths, {operations} operations -> {args.out}"
    )


if __name__ == "__main__":
    main()
